<?php
// module/Album/view/album/album/add.phtml:

$title = 'Delete album';
$this->headTitle($title);
?>
<div class="col-md-4 col-md-offset-4">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Are you sure that you want to delete
        '<?php echo $this->escapeHtml($album->title); ?>' by
        '<?php echo $this->escapeHtml($album->artist); ?>'?
    </p>
    <?php
    $url = $this->url('album', array(
        'action' => 'delete',
        'id' => $this->id,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>"/>
            <input type="submit" class="btn btn-primary" name="del" value="Yes"/>
            <input type="submit" class="btn btn-danger" name="del" value="No"/>
        </div>
    </form>
