<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>
<div class="col-md-4 col-md-offset-4">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
    <div class="form-group">
        <label for="title">Title</label>
        <?php echo $this->formRow($form->get('title')); ?>
    </div>
    <div class="form-group">
        <label for="title">Artist</label>
        <?php echo $this->formRow($form->get('artist')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('album', array('action' => 'index'));?>" class="btn btn-danger">Cancel</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>
